name: Rube-ios
options:
  bundleIdPrefix: com.rube
packages:
  Appwrite:
    url: https://github.com/appwrite/sdk-for-apple
    from: 13.5.0
  ServiceLifecycle:
    url: https://github.com/swift-server/swift-service-lifecycle.git
    from: 2.9.1
  AsyncAlgorithms:
    url: https://github.com/apple/swift-async-algorithms.git
    from: 1.1.1
  SwiftOpenAI:
    url: https://github.com/jamesrochabrun/SwiftOpenAI
    from: 4.4.8
  Composio:
    url: https://github.com/chabhishek420/composio-swifft
    branch: main
  OpenAI:
    url: https://github.com/MacPaw/OpenAI.git
    from: 0.4.7

targets:
  Rube-ios:
    type: application
    platform: iOS
    deploymentTarget: "18.0"
    sources: [Rube-ios]
    info:
      path: Rube-ios/Info.plist
      properties:
        CFBundleDisplayName: "Rube"
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        UILaunchScreen:
          UIColorName: "LaunchBackgroundColor"
        CFBundleURLTypes:
          - CFBundleTypeRole: Editor
            CFBundleURLName: com.rube.ios
            CFBundleURLSchemes: [rube]
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.rube.ios
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
    dependencies:
      - package: Appwrite
      - package: ServiceLifecycle
        product: ServiceLifecycle
      - package: AsyncAlgorithms
        product: AsyncAlgorithms
      - package: SwiftOpenAI
        product: SwiftOpenAI
      - package: Composio
        product: Composio
      - package: OpenAI
        product: OpenAI

  Rube-iosTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "18.0"
    sources: [Rube-iosTests]
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: Rube-ios

schemes:
  Rube-ios:
    build:
      targets:
        Rube-ios: [run, test, profile, analyze]
    test:
      targets:
        - Rube-iosTests
